# Docker Compose configuration for Contact Agenda API
# Production-ready multi-container setup

version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: contact-agenda-api
    ports:
      - "8080:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/contacts.db
    volumes:
      - contact_data:/app/data
    networks:
      - contact-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/swagger"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.contactagenda.service=backend"
      - "com.contactagenda.version=1.0"

  # Frontend Service
  frontend:
    build:
      context: ./contact-agenda-frontend
      dockerfile: Dockerfile
    container_name: contact-agenda-frontend
    ports:
      - "3000:8080"
    networks:
      - contact-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "com.contactagenda.service=frontend"
      - "com.contactagenda.version=1.0"
    depends_on:
      backend:
        condition: service_healthy

# Named volumes for data persistence
volumes:
  contact_data:
    driver: local
    labels:
      - "com.contactagenda.volume=database"

# Custom network for service communication
networks:
  contact-network:
    driver: bridge
    labels:
      - "com.contactagenda.network=main"
