version: '3.8'

services:
  # PostgreSQL Database Service
  database:
    image: postgres:15-alpine
    container_name: contact-agenda-db
    environment:
      POSTGRES_DB: contactagenda
      POSTGRES_USER: contactuser
      POSTGRES_PASSWORD: contact123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - contact-agenda-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contactuser -d contactagenda"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile.api-only
    container_name: contact-agenda-api
    ports:
      - "8081:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=database;Database=contactagenda;Username=contactuser;Password=contact123
    depends_on:
      database:
        condition: service_healthy
    networks:
      - contact-agenda-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health || true"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend Service
  frontend:
    build:
      context: ./contact-agenda-frontend
      dockerfile: Dockerfile
    container_name: contact-agenda-frontend
    ports:
      - "3000:8080"
    depends_on:
      - api
    networks:
      - contact-agenda-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health || true"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Database Admin Tool (Optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: contact-agenda-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@contact.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      - contact-agenda-network
    profiles:
      - admin

networks:
  contact-agenda-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  contact_data:
    driver: local
